[package]
name = "wasm_assignment"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
json = "0.12.4"
wasm-bindgen = "0.2.91"
wasm-bindgen-test = "0.3.0"
